<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Categoria;
use App\Models\NivelEducativo;

class CategoriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get nivel educativo IDs
        $gradoMedio = NivelEducativo::where('nombre_nivel', 'Ciclos de Grado Medio')->first()->id;
        $gradoSuperior = NivelEducativo::where('nombre_nivel', 'Ciclos de Grado Superior')->first()->id;
        $universidad = NivelEducativo::where('nombre_nivel', 'Universidades')->first()->id;
        $master = NivelEducativo::where('nombre_nivel', 'Máster')->first()->id;

        $categorias = [
            // CICLOS DE GRADO MEDIO
                ['nombre_categoria' => 'Actividades Ecuestres', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Guía en el Medio Natural y de Tiempo Libre', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Gestión Administrativa', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Aprovechamiento y Conservación del Medio Natural', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Jardinería y Floristería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Producción Agroecológica', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Producción Agropecuaria', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Impresión Gráfica', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Postimpresión y Acabados Gráficos', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Preimpresión Digital', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Actividades Comerciales', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Comercialización de Productos Alimentarios', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Construcción', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Obras de Interior, Decoración y Rehabilitación', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Instalaciones Eléctricas y Automáticas', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Instalaciones de Telecomunicaciones', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Redes y Estaciones de Tratamiento de Aguas', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Conformado por Moldeo de Metales y Polímeros', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mecanizado', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Montaje de Estructuras e Instalación de Sistemas Aeronáuticos', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Soldadura y Calderería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Joyería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Cocina y Gastronomía', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Comercialización de Productos Alimentarios', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Servicios en Restauración', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Estética y Belleza', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Peluquería y Cosmética Capilar', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Vídeo Disc-Jockey y Sonido', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Aceites de Oliva y Vinos', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Elaboración de Productos Alimenticios', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Panadería, Repostería y Confitería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Excavaciones y Sondeos', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Piedra Natural', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Sistemas Microinformáticos y Redes', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Instalaciones Frigoríficas y de Climatización', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Instalaciones de Producción de Calor', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mantenimiento Electromecánico', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Carpintería y Mueble', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Instalación y Amueblamiento', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Procesado y Transformación de la Madera', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Cultivos Acuícolas', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mantenimiento y Control de la Maquinaria de Buques y Embarcaciones', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Navegación y Pesca de Litoral', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Operaciones Subacuáticas e Hiperbáricas', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Operaciones de Laboratorio', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Planta Química', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Emergencias Sanitarias', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Farmacia y Parafarmacia', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Cuidados Auxiliares de Enfermería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Emergencias y Protección Civil', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Sanidad Ambiental Aplicada', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Seguridad', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Atención a Personas en Situación de Dependencia', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Calzado y Complementos de Moda', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Confección y Moda', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Fabricación y Ennoblecimiento de Productos Textiles', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Carrocería', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Conducción de Vehículos de Transporte por Carretera', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Electromecánica de Maquinaria', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Electromecánica de Vehículos Automóviles', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mantenimiento de Embarcaciones de Recreo', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mantenimiento de Estructuras de Madera y Mobiliario de Embarcaciones de Recreo', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Mantenimiento de Material Rodante Ferroviario', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Montaje de Estructuras e Instalación de Sistemas Aeronáuticos', 'nivel_educativo_id' => $gradoMedio],
                ['nombre_categoria' => 'Fabricación de Productos Cerámicos', 'nivel_educativo_id' => $gradoMedio],

            // CICLOS DE GRADO SUPERIOR
                ['nombre_categoria' => 'Acondicionamiento Físico', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Enseñanza y Animación Sociodeportiva', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Administración y Finanzas', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Asistencia a la Dirección', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Ganadería y Asistencia en Sanidad Animal', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Gestión Forestal y del Medio Natural', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Paisajismo y Medio Rural', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño y Edición de Publicaciones Impresas y Multimedia', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño y Gestión de la Producción Gráfica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Artista Fallero y Construcción de Escenografías', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Comercio Internacional', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Gestión de Ventas y Espacios Comerciales', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Marketing y Publicidad', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Transporte y Logística', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Organización y Control de Obras de Construcción', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Proyectos de Edificación', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Proyectos de Obra Civil', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Automatización y Robótica Industrial', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Electromedicina Clínica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento Electrónico', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Superior en Sistemas Electrotécnicos y Automatizados', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Sistemas de Telecomunicaciones e Informáticos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Centrales Eléctricas', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Eficiencia Energética y Energía Solar Térmica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Energías Renovables', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Gestión del Agua', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Construcciones Metálicas', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño en Fabricación Mecánica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Programación de la Producción en Fabricación Mecánica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Programación de la Producción en Moldeo de Metales y Polímeros', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Óptica de Anteojería', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Agencias de Viajes y Gestión de Eventos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Dirección de Cocina', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Dirección de Servicios de Restauración', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Gestión de Alojamientos Turísticos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Guía, Información y Asistencias Turísticas', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Asesoría de Imagen Personal y Corporativa', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Caracterización y Maquillaje Profesional', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Estilismo y Dirección de Peluquería', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Estética Integral y Bienestar', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Termalismo y Bienestar', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Animaciones 3D, Juegos y Entornos Interactivos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Iluminación, Captación y Tratamiento de Imagen', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Producción de Audiovisuales y Espectáculos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Realización de Proyectos Audiovisuales y Espectáculos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Sonido para Audiovisuales y Espectáculos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Procesos y Calidad en la Industria Alimentaria', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Vitivinicultura', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Administración de Sistemas Informáticos en Red', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Desarrollo de Aplicaciones Multiplataforma', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Desarrollo de Aplicaciones Web', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Desarrollo de Proyectos de Instalaciones Térmicas y de Fluidos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento de Instalaciones Térmicas y de Fluidos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mecatrónica Industrial', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Prevención de Riesgos Profesionales', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño y Amueblamiento', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Acuicultura', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Organización del Mantenimiento de Maquinaria de Buques y Embarcaciones', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Transporte Marítimo y Pesca de Altura', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Fabricación de Productos Farmacéuticos, Biotecnológicos y Afines', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Laboratorio de Análisis y de Control de Calidad', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Química Industrial', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Anatomía Patológica y Citodiagnóstico', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Audiología Protésica', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Documentación y Administración Sanitarias', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Higiene Bucodental', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Imagen para el Diagnóstico y Medicina Nuclear', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Laboratorio Clínico y Biomédico', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Ortoprótesis y Productos de Apoyo', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Prótesis Dentales', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Radioterapia y Dosimetría', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Dietética', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Coordinación de Emergencias y Protección Civil', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Educación y Control Ambiental', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Prevención de Riesgos Profesionales', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Química y Salud Ambiental', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Animación Sociocultural y Turística', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Educación Infantil', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Formación para la Movilidad Segura y Sostenible', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Integración Social', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mediación Comunicativa', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Promoción de Igualdad de Género', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño Técnico en Textil y Piel', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Diseño y Producción de Calzado y Complementos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Patronaje y Moda', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Vestuario a Medida y de Espectáculos', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Automoción', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento Aeromecánico de Aviones con Motor de Pistón', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento Aeromecánico de Aviones con Motor de Turbina', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento Aeromecánico de Helicópteros con Motor de Pistón', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento Aeromecánico de Helicópteros con Motor de Turbina', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Mantenimiento de Sistemas Electrónicos y Aviónicos de Aeronaves', 'nivel_educativo_id' => $gradoSuperior],
                ['nombre_categoria' => 'Desarrollo y Fabricación de Productos Cerámicos', 'nivel_educativo_id' => $gradoSuperior],
            
            // UNIVERSIDADES
                ['nombre_categoria' => 'Administración de Empresas', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Administración y Dirección de Empresas', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Arquitectura', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Biología', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Biotecnología', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ciencia de Datos', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ciencias Ambientales', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ciencias de la Actividad Física y del Deporte', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ciberseguridad', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Comunicación Audiovisual', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Criminología', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Derecho', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Desarrollo de Videojuegos', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Diseño', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Economía', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Educación Infantil', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Educación Primaria', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Enfermería', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Farmacia', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Filología Hispánica', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Filosofía', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Física', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Fisioterapia', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Historia', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Historia del Arte', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ingeniería Biomédica', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ingeniería Civil', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ingeniería de Software', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ingeniería Informática', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Ingeniería Mecánica', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Inteligencia Artificial', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Marketing', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Matemáticas', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Medicina', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Nutrición Humana y Dietética', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Odontología', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Periodismo', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Psicología', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Química', 'nivel_educativo_id' => $universidad],
                ['nombre_categoria' => 'Veterinaria', 'nivel_educativo_id' => $universidad],
            
            // Máster
                ['nombre_categoria' => 'Marketing Digital', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Logística', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Inteligencia Artificial y Big Data', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Dirección de Empresas (MBA)', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Ciberseguridad', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Desarrollo Web', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Recursos Humanos', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Finanzas', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Biotecnología', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Gestión de Proyectos', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Comercio Internacional', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Energías Renovables', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Psicología Clínica', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Transformación Digital', 'nivel_educativo_id' => $master],
                ['nombre_categoria' => 'Abogacía', 'nivel_educativo_id' => $master]
        ];

        foreach ($categorias as $categoria) {
            Categoria::create($categoria);
        }
    }
}
